project:
  type: website

website:
  title: "Sebastian Metz"
  navbar:
    background: dark
    search: true
    pinned: true
    
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - publications.qmd
      - text: Portafolio
        menu: 
          - text: All Portafolio
            href: portafolio/index.qmd
          - text: Bioinfo
            href: portafolio/bio.qmd
          - text: Other
            href: portafolio/other.qmd
          
    
    right:
      - icon: "twitter"
        href: https://twitter.com/seba_metz
      - icon: "github"
        href: https://github.com/sebametz
      - icon: "linkedin"
        href: https://www.linkedin.com/in/sebastian-metz-783120190/
      - icon: envelope
        href: mailto:metz.seba91@gmail.com
    
  page-footer:
    left: "Blog made by Sebastian Metz. License: [CS BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)" 
    right: 
      - icon: "twitter"
        href: https://twitter.com/seba_metz
      - icon: "github"
        href: https://github.com/sebametz
      - icon: "linkedin"
        href: https://www.linkedin.com/in/sebastian-metz-783120190/
      - icon: envelope
        href: mailto:metz.seba91@gmail.com

format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    toc: true

editor: visual

